name: Build OpenWrt MR32 Initramfs + Sysupgrade

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libncurses5-dev gawk git subversion wget unzip python3 rsync

      - name: Clone OpenWrt
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git
          cd openwrt
          git checkout v24.10.0
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp ../.config .config
          # Патчим Makefile для MR32, чтобы выпускал initramfs и sysupgrade
          sed -i '/Device\/meraki_mr32/,/endef/ {
              /IMAGE\/trx/ a\  IMAGE\/initramfs.trx := append-uboot | pad-to $$(BLOCKSIZE) | append-rootfs | pad-rootfs | append-metadata
              /endef/ i\  IMAGE\/sysupgrade.bin := append-rootfs | pad-rootfs | append-metadata
          }' target/linux/bcm53xx/image/Makefile
          make defconfig
          make -j$(nproc)

      - name: Collect artifacts
        run: |
          mkdir artifacts
          find openwrt/bin/targets/bcm53xx/generic -name "*initramfs*.trx" -exec cp {} artifacts/mr32-initramfs.bin \;
          find openwrt/bin/targets/bcm53xx/generic -name "*sysupgrade*.bin" -exec cp {} artifacts/mr32-sysupgrade.bin \;
          ls -lh artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mr32-images
          path: artifacts/*
          compression-level: 0
          if-no-files-found: error